package g6.gcm.core.factories;

public enum DTOsFactory {

    USER, REPORT, LOGIN, CREDIT_CARD, CONTENT_EDITOR, CONTENT_MANAGER, COMPANY_MANAGER, CITY, MAP_COLLECTION, MAP, TOUR,
    SITE, SUBSCRIPTION, SUBSCRIPTION_RENEWAL, ONE_SHOT_DEAL, ACTIVITY, COORDINATES, PURCHASE, NOTIFICATION, PRICE_REQUEST, SITE_CLASSIFICATION

}
