package g6.gcm.core.factories;

import g6.gcm.core.interfaces.Request;

public enum ServersCommands implements Request {
  INITIAL_STATE, RETRY_LOGIN, SIGN_IN_COSTUMER, SUCCESSFUL_SIGN_UP, FAILED_SIGN_UP, SUCCESSFUL_CREDIT_CARD_INSERT, FAILED_CREDIT_CARD_INSERT, SIGN_IN_EMPLOYEE, SUCCESSFUL_ONESHOTDEAL_CREATION, FAILED_ONESHOTDEAL_CREATION, SUCCESSFUL_SUBSCRIPTION_CREATION, FAILED_SUBSCRIPTION_CREATION, SUBSCRIPTION_NOT_EXTENDED, SUBSCRIPTION_SUCCESSFULLY_EXTENDED, SCCESSFUL_UPDATE_PROFILE, CREDIT_INFO_TRANSFERED, CREDIT_CARD_DELETED, SUCCESSFUL_UPDATE_PASSWORD, PRICE_REQUEST_DELETED, PRICE_REQUEST_HAS_BEEN_ADDED, ALREADY_LOGGED_IN, EXIT_FROM_SYSTEM, SUCCESSFUL_CITY_UPDATE, SUCCESSFULL_SITE_CREATION, SUCCESSFULL_SITE_DELETION, MAP_SAVED, SUCCESSFUL_CITY_CREATE, MAP_CREATED,
}
